---
- name: Install openssh-server
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - openssh-server

# https://github.com/microsoft/WSL/issues/3621
- name: Create /run/sshd inside containers
  ansible.builtin.file:
    path: /run/sshd
    state: directory
    mode: "0755"
    owner: root
  when: ansible_virtualization_type in ['docker', 'podman', 'lxc', 'containerd', 'VirtualPC']
